//
// Generated by JTB 1.3.2
//

package com.ironiacorp.learndb.parser.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public @SuppressWarnings("all") interface Node extends java.io.Serializable {
   public void accept(com.ironiacorp.learndb.parser.visitor.Visitor v);
   public <R,A> R accept(com.ironiacorp.learndb.parser.visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(com.ironiacorp.learndb.parser.visitor.GJNoArguVisitor<R> v);
   public <A> void accept(com.ironiacorp.learndb.parser.visitor.GJVoidVisitor<A> v, A argu);
}

