/* Generated By:JJTree&JavaCC: Do not edit this line. eg2Constants.java */
package com.ironiacorp.learndb.parser;

public @SuppressWarnings("all") interface eg2Constants {

  int EOF = 0;
  int INTEGER_LITERAL = 6;
  int DECIMAL_LITERAL = 7;
  int HEX_LITERAL = 8;
  int OCTAL_LITERAL = 9;
  int IDENTIFIER = 10;
  int LETTER = 11;
  int DIGIT = 12;
  int ADD = 13;
  int ALL = 14;
  int ALLOCATE = 15;
  int ALTER = 16;
  int AND = 17;
  int ANY = 18;
  int ARE = 19;
  int AS = 20;
  int ASC = 21;
  int ASSERTION = 22;
  int AT = 23;
  int AUTHORIZATION = 24;
  int AVG = 25;
  int BEGIN = 26;
  int BETWEEN = 27;
  int BINARY = 28;
  int BIT = 29;
  int BOTH = 30;
  int BY = 31;
  int CASCADE = 32;
  int CASCADED = 33;
  int CASE = 34;
  int CAST = 35;
  int CHAR = 36;
  int CHARACTER = 37;
  int CHARACTER_LENGTH = 38;
  int CHECK = 39;
  int CLOSE = 40;
  int COALESCE = 41;
  int COLLATE = 42;
  int COLLATION = 43;
  int COLUMN = 44;
  int COMMIT = 45;
  int CONNECT = 46;
  int CONNECTION = 47;
  int CONSTRAINT = 48;
  int CONSTRAINTS = 49;
  int CONTINUE = 50;
  int CONVERT = 51;
  int CORRESPONDING = 52;
  int COUNT = 53;
  int CREATE = 54;
  int CURRENT = 55;
  int CURRENT_DATE = 56;
  int CURRENT_TIME = 57;
  int CURRENT_TIMESTAMP = 58;
  int CURRENT_USER = 59;
  int CURSOR = 60;
  int D = 61;
  int DEALLOCATE = 62;
  int DEC = 63;
  int DECIMAL = 64;
  int DECLARE = 65;
  int _DEFAULT = 66;
  int DEFERRABLE = 67;
  int DEFERRED = 68;
  int DELETE = 69;
  int DESC = 70;
  int DESCRIBE = 71;
  int DIAGNOSTICS = 72;
  int DISCONNECT = 73;
  int DISTINCT = 74;
  int DOUBLE = 75;
  int DROP = 76;
  int ELSE = 77;
  int END = 78;
  int ENDEXEC = 79;
  int ESCAPE = 80;
  int EXCEPT = 81;
  int EXCEPTION = 82;
  int EXEC = 83;
  int EXECUTE = 84;
  int EXISTS = 85;
  int EXTERNAL = 86;
  int FALSE = 87;
  int FETCH = 88;
  int FIRST = 89;
  int FLOAT = 90;
  int FOR = 91;
  int FOREIGN = 92;
  int FOUND = 93;
  int FROM = 94;
  int FULL = 95;
  int FUNCTION = 96;
  int GET = 97;
  int GLOBAL = 98;
  int GO = 99;
  int GOTO = 100;
  int GRANT = 101;
  int GROUP = 102;
  int HAVING = 103;
  int HOUR = 104;
  int IDENTITY = 105;
  int IMMEDIATE = 106;
  int IN = 107;
  int INDICATOR = 108;
  int INITIALLY = 109;
  int INNER = 110;
  int INPUT = 111;
  int INSENSITIVE = 112;
  int INSERT = 113;
  int INT = 114;
  int INTEGER = 115;
  int INTERSECT = 116;
  int INTO = 117;
  int IS = 118;
  int ISOLATION = 119;
  int JOIN = 120;
  int KEY = 121;
  int LAST = 122;
  int LEFT = 123;
  int LIKE = 124;
  int LOWER = 125;
  int MATCH = 126;
  int MAX = 127;
  int MIN = 128;
  int MINUTE = 129;
  int MODULE = 130;
  int NATURAL = 131;
  int NEXT = 132;
  int NO = 133;
  int NOT = 134;
  int NULL = 135;
  int NULLIF = 136;
  int NUMERIC = 137;
  int OF = 138;
  int ON = 139;
  int ONLY = 140;
  int OPEN = 141;
  int OPTION = 142;
  int OR = 143;
  int ORDER = 144;
  int OUTER = 145;
  int OUTPUT = 146;
  int OVERLAPS = 147;
  int PAD = 148;
  int PARTIAL = 149;
  int PREPARE = 150;
  int PRESERVE = 151;
  int PRIMARY = 152;
  int PRIOR = 153;
  int PRIVILEGES = 154;
  int PROCEDURE = 155;
  int PUBLIC = 156;
  int READ = 157;
  int REAL = 158;
  int REFERENCES = 159;
  int RELATIVE = 160;
  int RESTRICT = 161;
  int REVOKE = 162;
  int RIGHT = 163;
  int ROLLBACK = 164;
  int ROWS = 165;
  int SCHEMA = 166;
  int SCROLL = 167;
  int SECOND = 168;
  int SELECT = 169;
  int SESSION_USER = 170;
  int SET = 171;
  int SMALLINT = 172;
  int SOME = 173;
  int SPACE = 174;
  int SQL = 175;
  int SQLCODE = 176;
  int SQLERROR = 177;
  int SQLSTATE = 178;
  int SUBSTRING = 179;
  int SUM = 180;
  int SYSTEM_USER = 181;
  int T = 182;
  int TABLE = 183;
  int TEMPORARY = 184;
  int TIMEZONE_HOUR = 185;
  int TIMEZONE_MINUTE = 186;
  int TO = 187;
  int TRANSACTION = 188;
  int TRANSLATE = 189;
  int TRANSLATION = 190;
  int TRUE = 191;
  int TS = 192;
  int UNION = 193;
  int UNIQUE = 194;
  int UNKNOWN = 195;
  int UPDATE = 196;
  int UPPER = 197;
  int USER = 198;
  int USING = 199;
  int VALUE = 200;
  int VALUES = 201;
  int VARBINARY = 202;
  int VARCHAR = 203;
  int VARYING = 204;
  int VIEW = 205;
  int WHENEVER = 206;
  int WHERE = 207;
  int WITH = 208;
  int WORK = 209;
  int WRITE = 210;
  int YEAR = 211;
  int BLOB = 212;
  int CLOB = 213;
  int CONTAINS = 214;
  int DATE = 215;
  int DAY = 216;
  int INCREMENT = 217;
  int INITIAL = 218;
  int INTERVAL = 219;
  int LEVEL = 220;
  int LOCKS = 221;
  int LOCKSIZE = 222;
  int REPEATABLE = 223;
  int SAVEPOINT = 224;
  int TIME = 225;
  int TIMESTAMP = 226;
  int TRUNCATE = 227;
  int UNCOMMITTED = 228;
  int AFTER = 229;
  int BEFORE = 230;
  int BOOLEAN = 231;
  int DATABASE = 232;
  int EMPTY = 233;
  int EXPLAIN = 234;
  int INDEX = 235;
  int LOCK = 236;
  int LONGINT = 237;
  int LONG = 238;
  int DOUBLE_QUOTE = 239;
  int PERCENT = 240;
  int AMPERSAND = 241;
  int QUOTE = 242;
  int LEFT_BRACE = 243;
  int RIGHT_BRACE = 244;
  int LEFT_PAREN = 245;
  int RIGHT_PAREN = 246;
  int ASTERISK = 247;
  int PLUS_SIGN = 248;
  int COMMA = 249;
  int MINUS_SIGN = 250;
  int PERIOD = 251;
  int SOLIDUS = 252;
  int COLON = 253;
  int DOUBLE_COLON = 254;
  int SEMICOLON = 255;
  int LESS_THAN_OPERATOR = 256;
  int LESS_THAN_OR_EQUALS_OPERATOR = 257;
  int EQUALS_OPERATOR = 258;
  int NOT_EQUALS_OPERATOR = 259;
  int NOT_EQUALS_OPERATOR2 = 260;
  int GREATER_THAN_OPERATOR = 261;
  int GREATER_THAN_OR_EQUALS_OPERATOR = 262;
  int QUESTION_MARK = 263;
  int UNDERSCORE = 264;
  int VERTICAL_BAR = 265;
  int LEFT_BRACKET = 266;
  int RIGHT_BRACKET = 267;
  int CONCATENATION_OPERATOR = 268;
  int FIELD_REFERENCE = 269;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"add\"",
    "\"all\"",
    "\"allocate\"",
    "\"alter\"",
    "\"and\"",
    "\"any\"",
    "\"are\"",
    "\"as\"",
    "\"asc\"",
    "\"assertion\"",
    "\"at\"",
    "\"authorization\"",
    "\"avg\"",
    "\"begin\"",
    "\"between\"",
    "\"binary\"",
    "\"bit\"",
    "\"both\"",
    "\"by\"",
    "\"cascade\"",
    "\"cascaded\"",
    "\"case\"",
    "\"cast\"",
    "\"char\"",
    "\"character\"",
    "\"character_length\"",
    "\"check\"",
    "\"close\"",
    "\"coalesce\"",
    "\"collate\"",
    "\"collation\"",
    "\"column\"",
    "\"commit\"",
    "\"connect\"",
    "\"connection\"",
    "\"constraint\"",
    "\"constraints\"",
    "\"continue\"",
    "\"convert\"",
    "\"corresponding\"",
    "\"count\"",
    "\"create\"",
    "\"current\"",
    "\"current_date\"",
    "\"current_time\"",
    "\"current_timestamp\"",
    "\"current_user\"",
    "\"cursor\"",
    "\"d\"",
    "\"deallocate\"",
    "\"dec\"",
    "\"decimal\"",
    "\"declare\"",
    "\"default\"",
    "\"deferrable\"",
    "\"deferred\"",
    "\"delete\"",
    "\"desc\"",
    "\"describe\"",
    "\"diagnostics\"",
    "\"disconnect\"",
    "\"distinct\"",
    "\"double\"",
    "\"drop\"",
    "\"else\"",
    "\"end\"",
    "\"end-exec\"",
    "\"escape\"",
    "\"except\"",
    "\"exception\"",
    "\"exec\"",
    "\"execute\"",
    "\"exists\"",
    "\"external\"",
    "\"false\"",
    "\"fetch\"",
    "\"first\"",
    "\"float\"",
    "\"for\"",
    "\"foreign\"",
    "\"found\"",
    "\"from\"",
    "\"full\"",
    "\"function\"",
    "\"get\"",
    "\"global\"",
    "\"go\"",
    "\"goto\"",
    "\"grant\"",
    "\"group\"",
    "\"having\"",
    "\"hour\"",
    "\"identity\"",
    "\"immediate\"",
    "\"in\"",
    "\"indicator\"",
    "\"initially\"",
    "\"inner\"",
    "\"input\"",
    "\"insensitive\"",
    "\"insert\"",
    "\"int\"",
    "\"integer\"",
    "\"intersect\"",
    "\"into\"",
    "\"is\"",
    "\"isolation\"",
    "\"join\"",
    "\"key\"",
    "\"last\"",
    "\"left\"",
    "\"like\"",
    "\"lower\"",
    "\"match\"",
    "\"max\"",
    "\"min\"",
    "\"minute\"",
    "\"module\"",
    "\"natural\"",
    "\"next\"",
    "\"no\"",
    "\"not\"",
    "\"null\"",
    "\"nullif\"",
    "\"numeric\"",
    "\"of\"",
    "\"on\"",
    "\"only\"",
    "\"open\"",
    "\"option\"",
    "\"or\"",
    "\"order\"",
    "\"outer\"",
    "\"output\"",
    "\"overlaps\"",
    "\"pad\"",
    "\"partial\"",
    "\"prepare\"",
    "\"preserve\"",
    "\"primary\"",
    "\"prior\"",
    "\"privileges\"",
    "\"procedure\"",
    "\"public\"",
    "\"read\"",
    "\"real\"",
    "\"references\"",
    "\"relative\"",
    "\"restrict\"",
    "\"revoke\"",
    "\"right\"",
    "\"rollback\"",
    "\"rows\"",
    "\"schema\"",
    "\"scroll\"",
    "\"second\"",
    "\"select\"",
    "\"session_user\"",
    "\"set\"",
    "\"smallint\"",
    "\"some\"",
    "\"space\"",
    "\"sql\"",
    "\"sqlcode\"",
    "\"sqlerror\"",
    "\"sqlstate\"",
    "\"substring\"",
    "\"sum\"",
    "\"system_user\"",
    "\"t\"",
    "\"table\"",
    "\"temporary\"",
    "\"timezone_hour\"",
    "\"timezone_minute\"",
    "\"to\"",
    "\"transaction\"",
    "\"translate\"",
    "\"translation\"",
    "\"true\"",
    "\"ts\"",
    "\"union\"",
    "\"unique\"",
    "\"unknown\"",
    "\"update\"",
    "\"upper\"",
    "\"user\"",
    "\"using\"",
    "\"value\"",
    "\"values\"",
    "\"varbinary\"",
    "\"varchar\"",
    "\"varying\"",
    "\"view\"",
    "\"whenever\"",
    "\"where\"",
    "\"with\"",
    "\"work\"",
    "\"write\"",
    "\"year\"",
    "\"blob\"",
    "\"clob\"",
    "\"contains\"",
    "\"date\"",
    "\"day\"",
    "\"increment\"",
    "\"initial\"",
    "\"interval\"",
    "\"level\"",
    "\"locks\"",
    "\"locksize\"",
    "\"repeatable\"",
    "\"savepoint\"",
    "\"time\"",
    "\"timestamp\"",
    "\"truncate\"",
    "\"uncommitted\"",
    "\"after\"",
    "\"before\"",
    "\"boolean\"",
    "\"database\"",
    "\"empty\"",
    "\"explain\"",
    "\"index\"",
    "\"lock\"",
    "\"bigint\"",
    "\"long\"",
    "\"\\\"\"",
    "\"%\"",
    "\"&\"",
    "\"\\\'\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\",\"",
    "\"-\"",
    "\".\"",
    "\"/\"",
    "\":\"",
    "\"::\"",
    "\";\"",
    "\"<\"",
    "\"<=\"",
    "\"=\"",
    "\"<>\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"?\"",
    "\"_\"",
    "\"|\"",
    "\"[\"",
    "\"]\"",
    "\"||\"",
    "\"->\"",
  };

}
