/* Generated By:JJTree: Do not edit this line. ./eg2TreeConstants.java */

package com.ironiacorp.learndb.parser;

public @SuppressWarnings("all") interface eg2TreeConstants
{
  public int JJTCREATESTATEMENT = 0;
  public int JJTTABLEDEFINITION = 1;
  public int JJTTABLEELEMENTLIST = 2;
  public int JJTTABLEELEMENT = 3;
  public int JJTCOLUMNDEFINITION = 4;
  public int JJTDEFAULTANDCONSTRAINTS = 5;
  public int JJTTABLECONSTRAINTDEFINITION = 6;
  public int JJTTABLECONSTRAINT = 7;
  public int JJTUNIQUECONSTRAINTDEFINITION = 8;
  public int JJTUNIQUESPECIFICATION = 9;
  public int JJTUNIQUECOLUMNLIST = 10;
  public int JJTREFERENTIALCONSTRAINTDEFINITION = 11;
  public int JJTREFERENCESSPECIFICATION = 12;
  public int JJTREFERENCEDTABLEANDCOLUMNS = 13;
  public int JJTREFERENTIALTRIGGEREDACTION = 14;
  public int JJTUPDATERULE = 15;
  public int JJTDELETERULE = 16;
  public int JJTUPDATEREFERENTIALACTION = 17;
  public int JJTDELETEREFERENTIALACTION = 18;
  public int JJTCOLUMNCONSTRAINTDEFINITION = 19;
  public int JJTCOLUMNCONSTRAINT = 20;
  public int JJTDATATYPEDDL = 21;
  public int JJTDATATYPECOMMON = 22;
  public int JJTCHARACTERSTRINGTYPE = 23;
  public int JJTCHARLENGTH = 24;
  public int JJTLOBTYPE = 25;
  public int JJTNUMERICTYPE = 26;
  public int JJTEXACTNUMERICTYPE = 27;
  public int JJTEXACTINTEGERTYPE = 28;
  public int JJTAPPROXIMATENUMERICTYPE = 29;
  public int JJTDOUBLETYPE = 30;
  public int JJTLENGTHANDMODIFIER = 31;
  public int JJTLENGTH = 32;
  public int JJTEXACTNUMBER = 33;
  public int JJTPRECISION = 34;
  public int JJTUINT_VALUE = 35;
  public int JJTSCALE = 36;
  public int JJTDATETIMETYPE = 37;


  public String[] jjtNodeName = {
    "createStatement",
    "tableDefinition",
    "tableElementList",
    "tableElement",
    "columnDefinition",
    "defaultAndConstraints",
    "tableConstraintDefinition",
    "tableConstraint",
    "uniqueConstraintDefinition",
    "uniqueSpecification",
    "uniqueColumnList",
    "referentialConstraintDefinition",
    "referencesSpecification",
    "referencedTableAndColumns",
    "referentialTriggeredAction",
    "updateRule",
    "deleteRule",
    "updateReferentialAction",
    "deleteReferentialAction",
    "columnConstraintDefinition",
    "columnConstraint",
    "dataTypeDDL",
    "dataTypeCommon",
    "characterStringType",
    "charLength",
    "LOBType",
    "numericType",
    "exactNumericType",
    "exactIntegerType",
    "approximateNumericType",
    "doubleType",
    "lengthAndModifier",
    "length",
    "exactNumber",
    "precision",
    "uint_value",
    "scale",
    "datetimeType",
  };
}
